### ISSUE TITLE
Weekly and Monthly Graphs Not Displaying Data Properly

### ISSUE THREAD

**Issue by lgp171188** [Glucosio/android#135]
Only the day view graph is correct. Please see the attached screenshots
![screenshot_2015-10-28-10-26-15](https://cloud.githubusercontent.com/assets/218870/10780047/0f488e06-7d5f-11e5-90d2-b8f1327c12c3.png)
![screenshot_2015-10-28-10-28-28](https://cloud.githubusercontent.com/assets/218870/10780048/0f4af1dc-7d5f-11e5-900f-ae5e27dee0a1.png)
![screenshot_2015-10-28-10-28-36](https://cloud.githubusercontent.com/assets/218870/10780046/0f422912-7d5f-11e5-9d60-b6a39b1c7213.png)

**Comment by bkerensa** [comment]
@lgp171188 Thank you for bringing this bug to our attention our android team has been notified we will investigate this and have a fix available and released ASAP.

**Comment by bkerensa** [comment]
@lgp171188 After looking into this more it appears you only have a single weeks worth of data so until you have multiple weeks the weekly graph is working properly actually. And once you have a couple months of data it will show monthly averages.

So this is how it is supposed to work and once you have enough entries these graphs will populate but absent enough data it cannot populate them when it has nothing to work with.

Closing this as wont fix but please reopen it once you have enough data if for some reason it is not displaying properly.

**Comment by lgp171188** [comment]
@bkerensa While the issue with the weekly and monthly chart data not getting displayed properly might be due to having a single week's data or lesser, the graph is still incorrect since the readings on the Y-axis scale are repeated -114, 114, 115, 115, 115, 116, 116. The daily graph doesn't have similar issues even when there was just one reading.

**Comment by lgp171188** [comment]
Also it would be better if the weekly and monthly graphs clearly said that there is not enough data instead of displaying some incorrect graph which the user has no clue about.
